from alembic import op
import sqlalchemy as sa
from typing import Union, Sequence
from rhesis.backend.app.models.guid import GUID



# revision identifiers, used by Alembic.
revision: str = 'a7e1303a11da'
down_revision: Union[str, None] = '88f39c501875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_metric',
    sa.Column('behavior_id', GUID(), nullable=False),
    sa.Column('metric_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('organization_id', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['behavior_id'], ['behavior.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('behavior_id', 'metric_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('behavior_metric')
    # ### end Alembic commands ###